import { Check, Pencil, Plus, Search, ShieldCheck, X } from 'lucide-react'
import { FormEvent, useMemo, useState } from 'react'
import './leadership-pages.css'

type Category = 'Institutions' | 'Departments' | 'Mailboxes' | 'Users' | 'Roles' | 'Knowledge sources' | 'Form types' | 'Canonical fields' | 'Routing rules' | 'Escalation rules' | 'Delivery schedules' | 'QA policies' | 'Tone profiles' | 'Retention settings'
type AdminRecord = { id: string; name: string; detail: string; status: string; updated: string }
type FormDefinition = { id: string; name: string; category: string; version: string; acceptedTypes: string; requiredFields: string; classificationThreshold: string; extractionThreshold: string; status: string; updated: string }
type CanonicalField = { id: string; key: string; label: string; dataType: string; validation: string; usedBy: string; usage: string; status: string; updated: string }

const categories: Category[] = ['Institutions', 'Departments', 'Mailboxes', 'Users', 'Roles', 'Knowledge sources', 'Form types', 'Canonical fields', 'Routing rules', 'Escalation rules', 'Delivery schedules', 'QA policies', 'Tone profiles', 'Retention settings']
const formDefinitions: FormDefinition[] = [
  { id: 'form-definition-transcript-auth', name: 'Official Transcript Authorization', category: 'Registrar authorization', version: 'v2026.1', acceptedTypes: 'PDF, JPG, PNG', requiredFields: 'Full name · Student ID · Request type · Recipient · Delivery · Copy count · Signature · Signature date', classificationThreshold: '≥ 90%', extractionThreshold: '≥ 88%', status: 'Active', updated: 'Aug 2, 2026' },
  { id: 'form-definition-aid-verification', name: 'Financial Aid Verification', category: 'Financial aid verification', version: 'v2026.2', acceptedTypes: 'PDF, JPG, PNG', requiredFields: 'Full name · Student ID · Attestation', classificationThreshold: '≥ 88%', extractionThreshold: '≥ 84%', status: 'Active', updated: 'Aug 2, 2026' },
  { id: 'form-definition-application-update', name: 'Application Update Request', category: 'Admissions profile update', version: 'v2026.1', acceptedTypes: 'PDF, DOCX', requiredFields: 'Applicant name · Application ID · Requested change', classificationThreshold: '≥ 90%', extractionThreshold: '≥ 85%', status: 'Active', updated: 'Aug 2, 2026' },
  { id: 'form-definition-billing-dispute', name: 'Student Account Dispute', category: 'Student accounts dispute', version: 'v2026.3', acceptedTypes: 'PDF, XLSX', requiredFields: 'Account reference · Disputed amount · Reason', classificationThreshold: '≥ 88%', extractionThreshold: '≥ 82%', status: 'Active', updated: 'Aug 2, 2026' },
]
const canonicalFields: CanonicalField[] = [
  { id: 'FIELD-01', key: 'student_full_name', label: 'Student full name', dataType: 'String', validation: 'Required · normalized name', usedBy: 'Transcript · Aid', usage: 'Record matching · response greeting', status: 'Required', updated: 'Jul 24, 2026' },
  { id: 'FIELD-02', key: 'student_identifier', label: 'Student identifier', dataType: 'String', validation: 'Institution student ID pattern', usedBy: 'Transcript · Aid', usage: 'Record matching · routing', status: 'Required', updated: 'Jul 24, 2026' },
  { id: 'FIELD-03', key: 'request_type', label: 'Request type', dataType: 'Enum', validation: 'Official transcript', usedBy: 'Transcript', usage: 'Classification · queue routing', status: 'Required', updated: 'Jul 22, 2026' },
  { id: 'FIELD-04', key: 'delivery_recipient', label: 'Delivery recipient', dataType: 'String', validation: 'Required text', usedBy: 'Transcript', usage: 'Draft composition · form review', status: 'Required', updated: 'Jul 22, 2026' },
  { id: 'FIELD-05', key: 'delivery_method', label: 'Delivery method', dataType: 'Enum', validation: 'Approved delivery method', usedBy: 'Transcript', usage: 'Delivery safeguards', status: 'Required', updated: 'Jul 22, 2026' },
  { id: 'FIELD-06', key: 'copy_count', label: 'Copy count', dataType: 'Integer', validation: 'Between 1 and 10', usedBy: 'Transcript', usage: 'Transcript fulfillment', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-07', key: 'authorization_signature', label: 'Authorization signature', dataType: 'Boolean', validation: 'Signed acknowledgement required', usedBy: 'Transcript', usage: 'Mandatory review rule', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-08', key: 'signature_date', label: 'Signature date', dataType: 'Date', validation: 'Required when signed', usedBy: 'Transcript', usage: 'Form validation', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-09', key: 'attestation', label: 'Attestation', dataType: 'Boolean', validation: 'Signed acknowledgement required', usedBy: 'Aid', usage: 'Financial aid validation', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-10', key: 'applicant_name', label: 'Applicant name', dataType: 'String', validation: 'Required text', usedBy: 'Application update', usage: 'Application record matching', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-11', key: 'application_identifier', label: 'Application ID', dataType: 'String', validation: 'Institution application ID pattern', usedBy: 'Application update', usage: 'Application record matching', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-12', key: 'requested_change', label: 'Requested change', dataType: 'String', validation: 'Required text', usedBy: 'Application update', usage: 'Application update routing', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-13', key: 'account_reference', label: 'Account reference', dataType: 'String', validation: 'Institution account ID pattern', usedBy: 'Account dispute', usage: 'Student account matching', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-14', key: 'disputed_amount', label: 'Disputed amount', dataType: 'Currency', validation: 'Positive currency amount', usedBy: 'Account dispute', usage: 'Dispute validation', status: 'Required', updated: 'Aug 2, 2026' },
  { id: 'FIELD-15', key: 'dispute_reason', label: 'Reason for dispute', dataType: 'String', validation: 'Required text', usedBy: 'Account dispute', usage: 'Dispute triage', status: 'Required', updated: 'Aug 2, 2026' },
]
const seed: Record<Category, AdminRecord[]> = {
  Institutions: [{ id: 'INST-01', name: 'Northstar Fictional University', detail: 'Primary operating scope', status: 'Active', updated: 'Aug 2, 2026' }, { id: 'INST-02', name: 'Riverbend Demonstration College', detail: 'Partner institution', status: 'Active', updated: 'Aug 1, 2026' }, { id: 'INST-03', name: 'Harborview Sample Institute', detail: 'Partner institution', status: 'Active', updated: 'Jul 30, 2026' }, { id: 'INST-04', name: 'Prairie Coast Test University', detail: 'Partner institution', status: 'Active', updated: 'Jul 29, 2026' }],
  Departments: [{ id: 'DEPT-01', name: 'Registrar', detail: 'Transcript and records correspondence', status: 'Active', updated: 'Aug 2, 2026' }, { id: 'DEPT-02', name: 'Admissions', detail: 'Applicant communications', status: 'Active', updated: 'Jul 29, 2026' }, { id: 'DEPT-03', name: 'Financial Aid', detail: 'Aid documentation workflows', status: 'Active', updated: 'Jul 28, 2026' }],
  Mailboxes: [{ id: 'MBX-01', name: 'registrar@northstar.example.test', detail: 'Registrar · Northstar Fictional University', status: 'Monitored', updated: 'Aug 2, 2026' }, { id: 'MBX-02', name: 'admissions@riverbend.example.test', detail: 'Admissions · Riverbend Demonstration College', status: 'Monitored', updated: 'Aug 1, 2026' }, { id: 'MBX-03', name: 'aid@harborview.example.test', detail: 'Financial Aid · Harborview Sample Institute', status: 'Monitored', updated: 'Jul 31, 2026' }],
  Users: [{ id: 'USR-01', name: 'Morgan Lee', detail: 'Program Administrator', status: 'Active', updated: 'Aug 2, 2026' }, { id: 'USR-02', name: 'Avery Quinn', detail: 'Registrar Reviewer', status: 'Active', updated: 'Aug 1, 2026' }, { id: 'USR-03', name: 'Taylor Moss', detail: 'Knowledge Owner', status: 'Active', updated: 'Jul 30, 2026' }],
  Roles: [{ id: 'ROLE-01', name: 'Program Administrator', detail: 'Network governance and controls', status: 'Active', updated: 'Jul 28, 2026' }, { id: 'ROLE-02', name: 'Department Reviewer', detail: 'Approve and hold drafts', status: 'Active', updated: 'Jul 28, 2026' }],
  'Knowledge sources': [{ id: 'KS-01', name: 'Registrar policy library', detail: 'Approved policy articles', status: 'Connected', updated: 'Aug 2, 2026' }, { id: 'KS-02', name: 'Admissions guidance repository', detail: 'Admissions response standards', status: 'Connected', updated: 'Jul 30, 2026' }],
  'Form types': [], 'Canonical fields': [],
  'Routing rules': [{ id: 'ROUTE-01', name: 'Transcript request routing', detail: 'Registrar mailbox → transcript queue', status: 'Enabled', updated: 'Aug 2, 2026' }, { id: 'ROUTE-02', name: 'High-risk financial aid', detail: 'Route to mandatory review', status: 'Enabled', updated: 'Jul 29, 2026' }],
  'Escalation rules': [{ id: 'ESC-01', name: 'Missing identity evidence', detail: 'Escalate to department specialist', status: 'Enabled', updated: 'Jul 25, 2026' }, { id: 'ESC-02', name: 'Potential records privacy issue', detail: 'Escalate immediately', status: 'Enabled', updated: 'Jul 25, 2026' }],
  'Delivery schedules': [{ id: 'REL-01', name: 'Registrar afternoon delivery', detail: '4:00 PM ET · weekdays', status: 'Active', updated: 'Aug 2, 2026' }, { id: 'REL-02', name: 'Admissions daily delivery', detail: '3:30 PM ET · weekdays', status: 'Active', updated: 'Jul 29, 2026' }],
  'QA policies': [{ id: 'QA-01', name: 'Registrar baseline QA', detail: '20% random · 100% high risk', status: 'Active', updated: 'Aug 2, 2026' }, { id: 'QA-02', name: 'Knowledge change safeguard', detail: '100% review on affected drafts', status: 'Available', updated: 'Aug 2, 2026' }],
  'Tone profiles': [{ id: 'TONE-01', name: 'Clear and supportive', detail: 'Default student-facing profile', status: 'Active', updated: 'Jul 28, 2026' }, { id: 'TONE-02', name: 'Formal policy notice', detail: 'Compliance communications', status: 'Active', updated: 'Jul 28, 2026' }],
  'Retention settings': [{ id: 'RET-01', name: 'Correspondence audit history', detail: 'Retain for 365 simulated days', status: 'Active', updated: 'Jul 31, 2026' }, { id: 'RET-02', name: 'Form extraction records', detail: 'Retain for 180 simulated days', status: 'Active', updated: 'Jul 31, 2026' }],
}

export default function AdministrationPage() {
  const [category, setCategory] = useState<Category>('Institutions')
  const [records, setRecords] = useState(seed)
  const [forms, setForms] = useState(formDefinitions)
  const [fields, setFields] = useState(canonicalFields)
  const [query, setQuery] = useState('')
  const [editing, setEditing] = useState<AdminRecord | null>(null)
  const [creating, setCreating] = useState(false)
  const [notice, setNotice] = useState('')
  const isFormCatalog = category === 'Form types'
  const isCanonicalCatalog = category === 'Canonical fields'
  const configuredCount = (item: Category) => item === 'Form types' ? forms.length : item === 'Canonical fields' ? fields.length : records[item].length
  const visible = useMemo(() => records[category].filter((record) => `${record.name} ${record.detail}`.toLowerCase().includes(query.toLowerCase())), [category, query, records])
  const visibleForms = useMemo(() => forms.filter((form) => `${form.name} ${form.requiredFields} ${form.acceptedTypes}`.toLowerCase().includes(query.toLowerCase())), [forms, query])
  const visibleFields = useMemo(() => fields.filter((field) => `${field.key} ${field.label} ${field.validation} ${field.usage}`.toLowerCase().includes(query.toLowerCase())), [fields, query])
  const openFormEdit = (form: FormDefinition) => setEditing({ id: form.id, name: form.name, detail: `${form.version} · ${form.requiredFields}`, status: form.status, updated: form.updated })
  const openFieldEdit = (field: CanonicalField) => setEditing({ id: field.id, name: field.label, detail: `${field.key} · ${field.dataType} · ${field.validation}`, status: field.status, updated: field.updated })
  const closeModal = () => { setEditing(null); setCreating(false) }
  const save = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get('name') ?? '').trim(); const detail = String(data.get('detail') ?? '').trim(); const status = String(data.get('status') ?? 'Active'); if (!name || !detail) return
    if (isFormCatalog) { if (editing) setForms((current) => current.map((form) => form.id === editing.id ? { ...form, name, status, updated: 'Aug 2, 2026' } : form)); else setForms((current) => [{ id: `FORM-CFG-${current.length + 1}`, name, category: 'Other', version: 'v1.0', acceptedTypes: 'PDF, JPG, PNG', requiredFields: detail, classificationThreshold: '≥ 90%', extractionThreshold: '≥ 85%', status, updated: 'Aug 2, 2026' }, ...current]) }
    else if (isCanonicalCatalog) { if (editing) setFields((current) => current.map((field) => field.id === editing.id ? { ...field, label: name, status, updated: 'Aug 2, 2026' } : field)); else setFields((current) => [{ id: `FIELD-CFG-${current.length + 1}`, key: name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/(^_|_$)/g, ''), label: name, dataType: 'String', validation: detail, usedBy: 'New definitions', usage: 'Classification ground truth', status, updated: 'Aug 2, 2026' }, ...current]) }
    else if (editing) setRecords((current) => ({ ...current, [category]: current[category].map((record) => record.id === editing.id ? { ...record, name, detail, status, updated: 'Aug 2, 2026' } : record) }))
    else setRecords((current) => ({ ...current, [category]: [{ id: `${category.slice(0, 3).toUpperCase()}-${String(current[category].length + 1).padStart(2, '0')}`, name, detail, status, updated: 'Aug 2, 2026' }, ...current[category]] }))
    setNotice(editing ? `${name} updated in this simulated environment.` : `${name} added to ${category.toLowerCase()}.`); closeModal()
  }
  const categoryDescription = isFormCatalog ? 'Approved form definitions used to classify incoming attachments; these are configuration ground truth, not extracted form instances.' : isCanonicalCatalog ? 'Stable normalized keys and validation rules used by form classification and downstream workflow controls.' : `${configuredCount(category)} configured records · demonstration-only local state`
  const addLabel = category === 'Form types' ? 'Add form definition' : category === 'Canonical fields' ? 'Add canonical field' : `Add ${category.slice(0, -1)}`
  return <div className="leadership-page administration-page">
    <div className="leadership-heading"><div><p className="eyebrow">Configuration</p><h1>Administration</h1><p>Local demonstration settings for institutions, policy controls, and correspondence operations.</p></div><div className="admin-trust"><ShieldCheck size={18} /><span>Configuration changes are simulated locally</span></div></div>
    {notice && <div className="page-toast" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss notification">×</button></div>}
    <div className="admin-layout"><nav className="admin-categories" aria-label="Administration categories">{categories.map((item) => <button className={item === category ? 'is-selected' : ''} key={item} onClick={() => { setCategory(item); setQuery('') }}>{item}<span>{configuredCount(item)}</span></button>)}</nav>
      <section className="leadership-panel admin-content"><div className="panel-heading"><div><h2>{category}</h2><p>{categoryDescription}</p></div><button className="button button-primary" onClick={() => setCreating(true)}><Plus size={16} />{addLabel}</button></div><div className="admin-toolbar"><label className="search-box"><Search size={16} /><span className="sr-only">Search {category}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${category.toLowerCase()}`} /></label><span>Showing {isFormCatalog ? visibleForms.length : isCanonicalCatalog ? visibleFields.length : visible.length} of {configuredCount(category)}</span></div>
        {isFormCatalog ? <FormDefinitionTable forms={visibleForms} onEdit={openFormEdit} /> : isCanonicalCatalog ? <CanonicalFieldTable fields={visibleFields} onEdit={openFieldEdit} /> : <GenericTable records={visible} category={category} onEdit={setEditing} />}
      </section></div>
    {(creating || editing) && <div className="modal-backdrop" role="presentation"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="admin-dialog-title"><div className="modal-heading"><div><p className="eyebrow">{category}</p><h2 id="admin-dialog-title">{editing ? `Edit ${category === 'Form types' ? 'form definition' : category === 'Canonical fields' ? 'canonical field' : category.slice(0, -1)}` : addLabel}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={closeModal}><X size={18} /></button></div><form onSubmit={save}><label>Name<input name="name" defaultValue={editing?.name ?? ''} autoFocus required /></label><label>{isFormCatalog ? 'Required fields' : isCanonicalCatalog ? 'Validation rule' : 'Configuration detail'}<textarea name="detail" defaultValue={editing?.detail ?? ''} rows={3} required /></label><label>Status<select name="status" defaultValue={editing?.status ?? 'Active'}><option>Active</option><option>Enabled</option><option>Available</option><option>Under review</option><option>Paused</option></select></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={closeModal}>Cancel</button><button type="submit" className="button button-primary">{editing ? 'Save changes' : addLabel}</button></div></form></section></div>}
  </div>
}

function FormDefinitionTable({ forms, onEdit }: { forms: FormDefinition[]; onEdit: (form: FormDefinition) => void }) {
  return <div className="table-scroll"><table><thead><tr><th>Form definition</th><th>Category</th><th>Version</th><th>Accepted file types</th><th>Required canonical fields</th><th>Confidence thresholds</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{forms.map((form) => <tr key={form.id}><td><b>{form.name}</b><small>{form.id}</small></td><td>{form.category}</td><td>{form.version}</td><td>{form.acceptedTypes}</td><td>{form.requiredFields}</td><td><b>Classify {form.classificationThreshold}</b><small>Extract {form.extractionThreshold}</small></td><td><span className="status-badge status-success"><Check size={13} />{form.status}</span></td><td><button className="icon-button" aria-label={`Edit ${form.name}`} onClick={() => onEdit(form)}><Pencil size={16} /></button></td></tr>)}</tbody></table>{forms.length === 0 && <div className="empty-table">No form definitions match this search. Clear the filter or add a governed definition.</div>}</div>
}

function CanonicalFieldTable({ fields, onEdit }: { fields: CanonicalField[]; onEdit: (field: CanonicalField) => void }) {
  return <div className="table-scroll"><table><thead><tr><th>Normalized key</th><th>Display label</th><th>Data type</th><th>Validation</th><th>Used by forms</th><th>Workflow usage</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{fields.map((field) => <tr key={field.id}><td><b>{field.key}</b><small>{field.id}</small></td><td>{field.label}</td><td>{field.dataType}</td><td>{field.validation}</td><td>{field.usedBy}</td><td>{field.usage}</td><td><span className="status-badge status-success"><Check size={13} />{field.status}</span></td><td><button className="icon-button" aria-label={`Edit ${field.label}`} onClick={() => onEdit(field)}><Pencil size={16} /></button></td></tr>)}</tbody></table>{fields.length === 0 && <div className="empty-table">No canonical fields match this search. Clear the filter or add a normalized field.</div>}</div>
}

function GenericTable({ records, category, onEdit }: { records: AdminRecord[]; category: Category; onEdit: (record: AdminRecord) => void }) {
  return <div className="table-scroll"><table><thead><tr><th>Name</th><th>Configuration</th><th>Status</th><th>Last updated</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><b>{record.name}</b><small>{record.id}</small></td><td>{record.detail}</td><td><span className="status-badge status-success"><Check size={13} />{record.status}</span></td><td>{record.updated}</td><td><button className="icon-button" aria-label={`Edit ${record.name}`} onClick={() => onEdit(record)}><Pencil size={16} /></button></td></tr>)}</tbody></table>{records.length === 0 && <div className="empty-table">No configured {category.toLowerCase()} match this search. Clear the filter or add a new record.</div>}</div>
}
