import { useEffect, useState } from 'react'
import { AlertTriangle, ChevronRight, PauseCircle, Save, ShieldCheck } from 'lucide-react'
import { Badge, Button, Modal, PageHeader } from '../components/shared'
import { useDemo } from '../context/DemoContext'
import type { AgentMode, QaPolicy } from '../types'
import './operations-pages.css'

const modes: Array<{ mode: AgentMode; detail: string }> = [
  { mode: 'Normal', detail: 'Configured sampling and safeguards apply.' }, { mode: 'Increased QA', detail: 'Additional human QA on selected requests.' }, { mode: 'Full Review', detail: 'Every eligible draft requires review.' }, { mode: 'Paused', detail: 'Automation remains staged, never delivered.' }, { mode: 'Knowledge Change', detail: 'Affected drafts wait for policy direction.' }, { mode: 'Emergency Hold', detail: 'Immediate hold across the selected scope.' },
]

export default function AgentControlsPage() {
  const { state, actions } = useDemo()
  const policy = state.policies.find((item) => item.requestType === 'Transcript request') ?? state.policies[0]
  const [draft, setDraft] = useState<QaPolicy | undefined>(policy)
  const [holdConfirm, setHoldConfirm] = useState(false)
  const [toast, setToast] = useState('')
  useEffect(() => setDraft(policy), [policy])
  if (!draft) return <div className="ops-page"><PageHeader title="Agent Controls" subtitle="No simulated policy is available." /></div>
  const changed = JSON.stringify(draft) !== JSON.stringify(policy)
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 4200) }
  const patch = <K extends keyof QaPolicy>(key: K, value: QaPolicy[K]) => setDraft((current) => current ? { ...current, [key]: value } : current)
  const percent = (key: 'headlessAutomationPercentage' | 'randomQaPercentage' | 'mandatoryHumanReviewPercentage' | 'minimumGroundingConfidence' | 'minimumExtractionConfidence', label: string, note: string) => <div className="policy-field"><label htmlFor={key}>{label}</label><small>{note}</small><div className="range-row"><input className="ops-range" id={key} type="range" min="0" max="100" value={draft[key]} onChange={(event) => patch(key, Number(event.target.value))} /><input className="ops-input" aria-label={`${label} percentage`} type="number" min="0" max="100" value={draft[key]} onChange={(event) => patch(key, Math.max(0, Math.min(100, Number(event.target.value))))} /></div></div>
  return <div className="ops-page">
    <PageHeader title="Agent Controls" subtitle="Configure explainable automation and delivery safeguards by operational scope." actions={<Button variant="primary" disabled={!changed} onClick={() => { actions.updatePolicy(draft.id, draft); notify('Registrar policy saved; simulated controls now apply.') }}><Save size={16} />Save changes</Button>} />
    <section className="ops-panel scope-bar" aria-label="Policy scope"><Badge tone="info">Northstar Fictional University</Badge><ChevronRight className="scope-arrow" size={16} /><Badge tone="info">Registrar</Badge><ChevronRight className="scope-arrow" size={16} /><Badge tone="info">Registrar Services</Badge><ChevronRight className="scope-arrow" size={16} /><Badge tone="info">Transcript request</Badge><span className="ops-muted" style={{ fontSize: 12 }}>Mailbox policy overrides department defaults.</span></section>
    <section className={`ops-banner ${draft.mode === 'Emergency Hold' || draft.mode === 'Paused' ? 'danger' : 'warning'}`}><ShieldCheck size={18} /><div><strong>Current mode: {draft.mode}</strong><p>{modes.find((item) => item.mode === draft.mode)?.detail} This is a local, simulated policy configuration.</p></div></section>
    <div className="controls-layout"><div>
      <section className="ops-panel"><div className="ops-panel-head"><h2>Operating mode</h2><span className="ops-muted">Select the oversight level</span></div><div className="mode-grid">{modes.map((item) => <button key={item.mode} type="button" className={`mode-option ${draft.mode === item.mode ? 'selected' : ''}`} onClick={() => item.mode === 'Emergency Hold' ? setHoldConfirm(true) : patch('mode', item.mode)}><strong>{item.mode}</strong><span>{item.detail}</span></button>)}</div></section>
      <section className="ops-panel"><div className="ops-panel-head"><h2>Automation and QA</h2><span className="ops-muted">Percentages update the policy summary immediately</span></div><div className="policy-grid">{percent('headlessAutomationPercentage', 'Headless automation', 'Eligible drafts may stage without a reviewer.')}{percent('randomQaPercentage', 'Random QA sample', 'Sampled after the delivery population is locked.')}{percent('mandatoryHumanReviewPercentage', 'Mandatory high-risk review', 'High-risk correspondence always receives human review.')}{percent('minimumGroundingConfidence', 'Minimum grounding confidence', 'Required evidence threshold before staging.')}{percent('minimumExtractionConfidence', 'Minimum extraction confidence', 'Required form-extraction confidence.')}</div></section>
      <section className="ops-panel"><div className="ops-panel-head"><h2>Delivery safeguards</h2><span className="ops-muted">Applies to the selected Registrar mailbox</span></div><div className="policy-check"><div><label htmlFor="hours">Business-hours-only delivery</label><small>Scheduled delivery occurs only during configured operating hours.</small></div><input id="hours" type="checkbox" checked={draft.businessHoursOnly} onChange={(event) => patch('businessHoursOnly', event.target.checked)} /></div><div className="policy-check"><div><label htmlFor="knowledgeHold">Hold drafts after knowledge change</label><small>Keep impacted staged drafts from simulated delivery until reviewed.</small></div><input id="knowledgeHold" type="checkbox" checked={draft.knowledgeChangeHold} onChange={(event) => patch('knowledgeChangeHold', event.target.checked)} /></div><div className="policy-check"><div><label htmlFor="paused">Pause this mailbox</label><small>Stops Registrar delivery while preserving staged drafts.</small></div><input id="paused" type="checkbox" checked={draft.releasesPaused} onChange={(event) => patch('releasesPaused', event.target.checked)} /></div><div className="policy-check"><div><label htmlFor="releaseTime">Scheduled delivery time</label><small>Time for the next controlled delivery.</small></div><input id="releaseTime" className="ops-input" style={{ width: 120 }} value={draft.scheduledReleaseTime} onChange={(event) => patch('scheduledReleaseTime', event.target.value)} /></div><div className="policy-check"><div><label htmlFor="frequency">Delivery frequency</label><small>How often approved responses are batched.</small></div><select id="frequency" className="ops-select" value={draft.releaseFrequency} onChange={(event) => patch('releaseFrequency', event.target.value)}><option>Weekdays</option><option>Every 2 hours</option><option>Daily</option><option>Manual only</option></select></div></section>
      <section className="ops-panel"><div className="ops-panel-head"><h2>Response standards</h2></div><div className="policy-check"><div><label htmlFor="tone">Tone profile</label><small>Applied to predefined correspondence variants.</small></div><select id="tone" className="ops-select" value={draft.toneProfile} onChange={(event) => patch('toneProfile', event.target.value)}><option>Clear and reassuring</option><option>Professional</option><option>Warm and concise</option></select></div></section>
    </div><aside className="ops-summary"><section className="ops-panel"><h2>Registrar sample configuration</h2><ul className="ops-mini-list"><li><span>Headless automation</span><strong>{draft.headlessAutomationPercentage}%</strong></li><li><span>Random QA sample</span><strong>{draft.randomQaPercentage}%</strong></li><li><span>Mandatory high-risk review</span><strong>{draft.mandatoryHumanReviewPercentage}%</strong></li><li><span>Delivery time</span><strong>{draft.scheduledReleaseTime}</strong></li><li><span>Affected staged drafts</span><strong>{state.releaseBatches[0]?.populationDraftIds.length ?? 0}</strong></li></ul><div style={{ marginTop: 14 }} className="change-dot">{changed ? 'Unsaved changes' : 'All changes saved'}</div><Button style={{ width: '100%', marginTop: 14 }} onClick={() => { patch('randomQaPercentage', 100); patch('mode', 'Full Review'); actions.setBatchQaToFullReview(state.releaseBatches[0]?.id ?? ''); notify('QA set to 100% for the Registrar demonstration scope.') }}><ShieldCheck size={16} />Set QA to 100%</Button><Button style={{ width: '100%', marginTop: 8 }} onClick={() => { patch('mode', 'Increased QA'); patch('randomQaPercentage', Math.max(35, draft.randomQaPercentage)); notify('Increased-QA mode prepared. Save changes to retain it.') }}><ShieldCheck size={16} />Enable increased QA</Button><Button style={{ width: '100%', marginTop: 8 }} variant={draft.releasesPaused ? 'secondary' : 'danger'} onClick={() => { patch('releasesPaused', !draft.releasesPaused); actions.setReleasePaused(!draft.releasesPaused); notify(draft.releasesPaused ? 'Automated deliveries resumed.' : 'Automated deliveries paused.') }}><PauseCircle size={16} />{draft.releasesPaused ? 'Resume deliveries' : 'Pause all deliveries'}</Button></section></aside></div>
    <Modal open={holdConfirm} title="Place Registrar scope on emergency hold?" destructive onClose={() => setHoldConfirm(false)} footer={<><Button onClick={() => setHoldConfirm(false)}>Cancel</Button><Button variant="danger" onClick={() => { patch('mode', 'Emergency Hold'); patch('releasesPaused', true); actions.setReleasePaused(true); setHoldConfirm(false); notify('Emergency hold prepared. Save changes to retain it.') }}><AlertTriangle size={16} />Set emergency hold</Button></>}><p>This simulated control pauses automated deliveries for the selected Registrar scope. Existing staged responses remain visible for review.</p></Modal>
    {toast && <div className="toast-local" role="status">{toast}</div>}
  </div>
}
